<?php
if($_GET["code"]=="daily"&&$_SESSION["useragent"]=="")
{
	header("location:?page=login");
}
if(isset($_POST["txtUsername"]))
{
	$username=$_POST{"txtUsername"};
    $password=$_POST{"txtPassword"};
    $sql="select * from gws_admin where username='$username' and password='$password'";
    $result=mysql_query($sql);  
    $count=mysql_num_rows($result);
    mysql_close($link);
    if($count>=1) 
    {
		$row=mysql_fetch_array($result);
		$_SESSION["useragent"]=$row["username"];
	}
	header("location:?page=daily");
}
if($_GET["page"]=="logout")
{
	unset($_SESSION["useragent"]);
	header("location:?page=login");
}
?>